config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  get "/check", to: "home#check"
  resources :disclaimers
  get '/dashboard', to: 'dashboard#index'
 
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  

    resources :disclaimers, only: [:create, :show] do
      member do 
      patch :continue

      get :download_pdf
      get :download_text_file
    end
  end

   # get "/users/current", to: "users#current"

  namespace :api do 
    post 'generate_disclaimer', to: 'openai#generate'

  end

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "disclaimers#index"
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_action :authenticate_user!

  def index 
    @disclaimers = current_user.disclaimers.order(created_at: :desc)
  end




end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<h1>Your Discalimers </h1>
<% @disclaimers.each do |disclaimer|%>
  <div>
    <strong> <%= disclaimer.message %><br>
      <strong>Statement:</strong>
      <p> <%= disclaimer.statement%>  </p>
    </div>
    <%= link_to "View Disclaimer", disclaimer_path(disclaimer) %>
    <%= link_to "Donwload PDF", download_pdf_disclaimer_path(disclaimer)%>
    <%= link_to "Donwload Text", download_text_file_disclaimer_path(disclaimer)%>
    <%= link_to "Delete Disclaimer", disclaimer_path(disclaimer), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
    <%= link_to "Edit Disclaimer", edit_disclaimer_path(disclaimer), method: :update   %>
    <hr>
  <%end%>
  <%= link_to "Home", root_path %>
  <% link_to "Sign Out", destroy_user_session_path, method: :delete,  data: { turbo_method: :delete } %>